/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WorkoutDayRouteImport } from './routes/workout.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDayRoute = WorkoutDayRouteImport.update({
  id: '/workout/$day',
  path: '/workout/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workouts': typeof WorkoutsRoute
  '/workout/$day': typeof WorkoutDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workouts': typeof WorkoutsRoute
  '/workout/$day': typeof WorkoutDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workouts': typeof WorkoutsRoute
  '/workout/$day': typeof WorkoutDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workouts' | '/workout/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workouts' | '/workout/$day'
  id: '__root__' | '/' | '/workouts' | '/workout/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkoutsRoute: typeof WorkoutsRoute
  WorkoutDayRoute: typeof WorkoutDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$day': {
      id: '/workout/$day'
      path: '/workout/$day'
      fullPath: '/workout/$day'
      preLoaderRoute: typeof WorkoutDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkoutsRoute: WorkoutsRoute,
  WorkoutDayRoute: WorkoutDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
